[application]
name = "kopuz"
default_platform = "desktop"

[application.assets]
base_path = "crates/kopuz/assets"

[bundle]
identifier = "com.temidaradev.kopuz"
publisher = "temidaradev"
icon = ["./assets/app.ico", "./assets/logo.png"]
category = "public.app-category.music"
targets = ["macos", "dmg", "nsis", "msi"]

[bundle.macos]
info_plist_path = "Info.plist"

[web.app]
title = "kopuz"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[web.tailwind]
input = "tailwind.css"
config = "tailwind.config.js"
