use std::{env, fs, path::PathBuf};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let manifest_dir = PathBuf::from(manifest_dir);
    let locales_dir = manifest_dir.join("locales");

    println!("cargo:rerun-if-changed={}", locales_dir.display());

    let mut languages: Vec<(String, String)> = vec![];

    for entry in fs::read_dir(&locales_dir).expect("locales directory not found") {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().is_some_and(|e| e == "ftl") {
            println!("cargo:rerun-if-changed={}", path.display());
            let code = path.file_stem().unwrap().to_str().unwrap().to_string();
            let content = fs::read_to_string(&path).unwrap();
            let name = extract_language_name(&content).unwrap_or_else(|| code.clone());
            languages.push((code, name));
        }
    }

    // English first, rest alphabetical by display name
    languages.sort_by(|a, b| {
        if a.0 == "en" {
            std::cmp::Ordering::Less
        } else if b.0 == "en" {
            std::cmp::Ordering::Greater
        } else {
            a.1.cmp(&b.1)
        }
    });

    let mut code = String::from("// Auto-generated by i18n/build.rs — do not edit\n\n");

    code.push_str("pub static AVAILABLE_LANGUAGES: &[(&str, &str)] = &[\n");
    for (lang_code, lang_name) in &languages {
        code.push_str(&format!("    (\"{lang_code}\", \"{lang_name}\"),\n"));
    }
    code.push_str("];\n\n");

    code.push_str("pub fn get_ftl_content(lang: &str) -> Option<&'static str> {\n");
    code.push_str("    match lang {\n");
    for (lang_code, _) in &languages {
        let path = locales_dir.join(format!("{lang_code}.ftl"));
        let path = path.display();
        code.push_str(&format!(
            "        \"{lang_code}\" => Some(include_str!(r#\"{path}\"#)),\n"
        ));
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    let out_dir = env::var("OUT_DIR").unwrap();
    let out_path = PathBuf::from(out_dir).join("locales.rs");
    fs::write(out_path, code).unwrap();
}

fn extract_language_name(content: &str) -> Option<String> {
    for line in content.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("language-name") {
            let rest = rest.trim();
            if let Some(rest) = rest.strip_prefix('=') {
                return Some(rest.trim().to_string());
            }
        }
    }
    None
}
