pub mod activity;
pub mod album;
pub mod artist;
pub mod favorites;
pub mod home;
pub mod library;
pub mod local;
pub mod playlists;
pub mod radio;
pub mod search;
pub mod server;
pub mod settings;
pub mod theme_editor;
#[cfg(not(target_arch = "wasm32"))]
pub mod ytdlp;
