name: build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: macos-latest
            system: aarch64-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v14
        with:
          name: rusic
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build package
        run: |
          nix build .#packages.${{ matrix.system }}.default
          cachix push rusic result
